#! /bin/sh

commit=$1
echo Pushing $1 to branch

git push ssh://gerrit.chromium.org:29418/chromiumos/chromite.git $commit:refs/for/master

#git push ssh://gerrit.chromium.org:29418/chromiumos/third_party/u-boot-next.git $commit:refs/for/chromeos-v2011.03
#git push ssh://gerrit.chromium.org:29418/chromiumos/third_party/u-boot.git $commit:refs/for/chromeos-v2011.03

