#!/usr/bin/env python3

import sys

import crc8

for fname in sys.argv[1:]:
    with open(fname, 'rb') as inf:
        hash = crc8.crc8()
        hash.update(inf.read())
        print(f'{hash.hexdigest():8s} {fname}')
#hash.update()
#with open('/tmp/tst', 'wb') as fd:
    #fd.write(b'\x00\x11\x23\x32\x1C\xAC\x23\x3F\x25\x47\x3D\xB7\xE2\xC5\x6D\xB5\xDF\xFB\x48\xD2\xB0\x60\xD0\xF5\xA7\x10\x96\xE0\x00\x00\x00\x00\x00\x00\x00\x00\xC5')
