#!/bin/bash

REPOS=(x86 dm fdt)
OTHER=(us)

# Do this first to avoid race conditions where repos have to fetch the same
# commit comiits
#git fetch us

for b in "${REPOS[@]}"; do
	(git fetch ${b}-public && git fetch ${b} )&
done

for b in "${OTHER[@]}"; do
	git fetch ${b} &
done
wait
