#!/bin/bash

REPOS=(x86 dm fdt rk)

# Do this first to avoid race conditions where repos have to fetch the same
# commit comiits
git fetch us

for b in "${REPOS[@]}"; do
	(git fetch ${b}-public && git fetch ${b} )&
done

wait

